global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'library-management-system'
    environment: 'development'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'library-management-system'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['127.0.0.1:8080']
        labels:
          application: 'library-management-system'
          instance: 'library-app-1'
          environment: 'development'
    scheme: 'http'
    scrape_interval: 15s
    honor_labels: false
    scrape_timeout: 10s
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*):.*'
        replacement: '$1'
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace



alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093 