name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_IMAGE: ghcr.io/pehlivanmert/library-management-system
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE:$DOCKER_TAG .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: pehlivanmert
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        run: docker push $DOCKER_IMAGE:$DOCKER_TAG

      - name: Push Docker image to Docker Hub
        run: |
          docker tag $DOCKER_IMAGE:$DOCKER_TAG pehlivanmert/library-management-system:$DOCKER_TAG
          docker push pehlivanmert/library-management-system:$DOCKER_TAG

      - name: Start services with docker-compose
        run: docker-compose -f docker-compose.dev.yml up -d

      - name: Wait for services to be healthy
        run: |
          echo "Waiting for services to be healthy..."
          sleep 30
          docker-compose -f docker-compose.dev.yml ps

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          docker-compose -f docker-compose.dev.yml up -d
          
          echo "Checking services health..."
          docker-compose -f docker-compose.dev.yml ps 

